### ISSUE TITLE
feature request: add git branch for each folder

### ISSUE THREAD

**Issue by towry** [PaulRosset/git-aware#1]
current output only contain status, folder name, it would be great to include git branch for each folder, because it is tedious to check each repo folder for branch.

For example, I have a monorepo app that has a folder named repos to contains git repos that are ignored by the monorepo, I can use gitaware to quick check each git repos's status and current branch.

**Comment by PaulRosset** [comment]
That's a great suggestion!

I released a new version with this feature.

Thank you for your feedback.
